version: '3.8'

services:
  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=6379
    ports:
      - "6379:6379"
    networks:
      - app-network

  thumbnail:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thumbnail_service
    command: ["go", "run", "cmd/thumbnail/main.go"]
    stdin_open: true
    tty: true
    depends_on:
      - redis
    networks:
      - app-network

# cli:
#   build:
#     context: .
#     dockerfile: Dockerfile
#   command: ["go", "run", "cmd/cli/main.go"]
#   depends_on:
#     - grpc-server
#   networks:
#     - app-network
#   volumes:
#     - ./downloads:/app/downloads
#   stdin_open: true
#   tty: true

networks:
  app-network:
    driver: bridge
